// Generated by gencpp from file wyx_pid/scan_range.msg
// DO NOT EDIT!


#ifndef WYX_PID_MESSAGE_SCAN_RANGE_H
#define WYX_PID_MESSAGE_SCAN_RANGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace wyx_pid
{
template <class ContainerAllocator>
struct scan_range_
{
  typedef scan_range_<ContainerAllocator> Type;

  scan_range_()
    : header()
    , min_range(0.0)
    , max_range(0.0)  {
    }
  scan_range_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , min_range(0.0)
    , max_range(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _min_range_type;
  _min_range_type min_range;

   typedef double _max_range_type;
  _max_range_type max_range;





  typedef boost::shared_ptr< ::wyx_pid::scan_range_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wyx_pid::scan_range_<ContainerAllocator> const> ConstPtr;

}; // struct scan_range_

typedef ::wyx_pid::scan_range_<std::allocator<void> > scan_range;

typedef boost::shared_ptr< ::wyx_pid::scan_range > scan_rangePtr;
typedef boost::shared_ptr< ::wyx_pid::scan_range const> scan_rangeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wyx_pid::scan_range_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wyx_pid::scan_range_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::wyx_pid::scan_range_<ContainerAllocator1> & lhs, const ::wyx_pid::scan_range_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.min_range == rhs.min_range &&
    lhs.max_range == rhs.max_range;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::wyx_pid::scan_range_<ContainerAllocator1> & lhs, const ::wyx_pid::scan_range_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace wyx_pid

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::wyx_pid::scan_range_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wyx_pid::scan_range_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wyx_pid::scan_range_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wyx_pid::scan_range_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wyx_pid::scan_range_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wyx_pid::scan_range_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wyx_pid::scan_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8be944a2188690435105faa477f17547";
  }

  static const char* value(const ::wyx_pid::scan_range_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8be944a218869043ULL;
  static const uint64_t static_value2 = 0x5105faa477f17547ULL;
};

template<class ContainerAllocator>
struct DataType< ::wyx_pid::scan_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wyx_pid/scan_range";
  }

  static const char* value(const ::wyx_pid::scan_range_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wyx_pid::scan_range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 min_range\n"
"float64 max_range\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::wyx_pid::scan_range_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wyx_pid::scan_range_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.min_range);
      stream.next(m.max_range);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct scan_range_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wyx_pid::scan_range_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wyx_pid::scan_range_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "min_range: ";
    Printer<double>::stream(s, indent + "  ", v.min_range);
    s << indent << "max_range: ";
    Printer<double>::stream(s, indent + "  ", v.max_range);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WYX_PID_MESSAGE_SCAN_RANGE_H
